In [1]:
import numpy as np


In [2]:
rands = np.random.choice(500, 500, replace=False)

In [11]:
np.random.randint(0,256, (10,10))

array([[162, 152,  95, 252, 254, 111,  27,  87,  38,  28],
       [ 29, 144,  99,  44,   0,  75,   9, 213, 250,  68],
       [235,  68, 195, 129, 244, 173, 245,  16,  97, 106],
       [151, 105, 156, 242, 172, 116,  42, 192,   6, 195],
       [ 61, 177, 250, 151, 102,   5,  16, 220, 145, 113],
       [203,   1, 213,  93, 119,  56, 190, 157,  31,  65],
       [ 57,  81,  10, 156, 147,  92, 174,  72, 124, 148],
       [216, 182, 199,  17, 117, 193,  82,  97, 225, 240],
       [138,  90, 253,  61,  28,  63, 170,   6, 215, 191],
       [ 29, 167, 127, 222, 217, 232, 181,  21, 130, 133]])

In [2]:
y_pred = np.array([1,2,3])
y_test = np.array([1,2,2])
tf = y_pred==y_test
tf

array([ True,  True, False], dtype=bool)

In [4]:
tf = tf.astype(int)

In [5]:
np.mean(tf)*100

66.666666666666657

In [16]:
p = np.zeros([6,6])
p[0][0] += 1
p

array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [8]:
np.sum(p)

3.0

In [13]:
np.argmax(p, axis=1)

array([0, 3, 1, 0, 0, 0])